version: '3'
volumes:
    mongodb_data:
        external: false
services:
    flask:
        container_name: annotator_flask
        restart: always
        build:
            context: .
            dockerfile: ./docker/production/Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - './datasets:/data/datasets'
            - './app:/workspace/app'
        environment:
          - FLASK_APP=app
          - FLASK_ENV=production
        command: 'gunicorn -w 4 -b 0.0.0.0:5000 app:app --config app/gunicorn_config.py'
        depends_on:
            - database
    database:
        image: mongo:latest
        container_name: annotator_mongodb
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - 'mongodb_data:/data/db'
        ports:
            - '27017:27017'
        command: 'mongod --smallfiles --logpath=/dev/null'
