version: "3"
volumes:
  mongodb_data:
    external: false

services:
  test:
    container_name: annotator_test
    build:
      context: .
      dockerfile: ./backend/tests/Dockerfile
    depends_on:
      - database
  database:
    image: mongo:4
    container_name: annotator_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
